name: Test ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 6 * * *"

jobs:
  ci:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: lint
        run: make fmt-check
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements/dev.txt
      - name: Test with pytest
        run: |
          docker-compose up -d
          sleep 45
          docker-compose logs console
          pytest -s -v -k "not SSL and not self_signed_SSL"
          docker-compose down -v
        working-directory: tests
      - name: Test SSL connection with pytest
        run: |
          enable_ssl=true docker-compose up -d
          sleep 45
          pytest -s -v -k "SSL"
        working-directory: tests
      - name: Test self-signed SSL connection with pytest
        run: |
          enable_ssl=true docker-compose up -d
          sleep 45
          pytest -s -v -k "self_signed_SSL"
        working-directory: tests
